annotations:
  category: CMS
apiVersion: v2
appVersion: 5.8.3
dependencies:
  - condition: mariadb.enabled
    name: mariadb
    repository: https://charts.bitnami.com/bitnami
    version: 10.x.x
  - condition: memcached.enabled
    name: memcached
    repository: https://charts.bitnami.com/bitnami
    version: 6.x.x
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 1.x.x
description: Biznet Gio Wordpress Hosting.
engine: gotpl
home: https://biznetgio.com
icon: https://bitnami.com/assets/stacks/wordpress/img/wordpress-stack-220x234.png
keywords:
  - application
  - blog
  - cms
  - http
  - php
  - web
  - wordpress
maintainers:
  - email: support@biznetgio.com
    name: Bitnami
name: gio-wordpress
sources:
  - https://github.com/bitnami/bitnami-docker-wordpress
  - https://wordpress.org/
version: 13.0.5
